### ISSUE TITLE
关于下载分P视频的音频

### ISSUE THREAD

**Issue by Reed-yang** [jingfelix/BiliFM#10]
Hi，学长
  在使用脚本时遇到了一个新问题，当试图下载分P视频的音频时，只能输入Bv号，但分P视频的地址是由Bv?p=2获取的，因此脚本无法解析分P视频的地址，当输入Bv号时仅能下载首个分P的音频。
  希望能添加关于分P视频下载的功能，可以选择下载指定分P或者下载该视频下的全部分P。
  该功能将对我帮助很大，希望您能拨冗完善！

Best regards,
Reed

**Comment by jingfelix** [comment]
晚上回去看一下，还没下班

**Comment by jingfelix** [comment]
已在 0.1.7 中支持，直接传入 BV 号即可。

**Comment by Reed-yang** [comment]
thx!
