### ISSUE TITLE
About downloading favlist's all audio

### ISSUE THREAD

**Issue by Reed-yang** [jingfelix/BiliFM#5]
Hi, jingfelix!

I'm wondering if you could add a function that **easily download audios from a favlist**, which is very useful because list all BV code for videos is bothering.

Best regards,
  Reed

**Comment by jingfelix** [comment]
I will have a look!

**Comment by jingfelix** [comment]
In BiliFM 0.1.6, you can now download audio from a fav list. Docs will be soon updated.

**Comment by Reed-yang** [comment]
> @Reed-yang In BiliFM 0.1.6, you can now download audio from a fav list. Docs will be soon updated.

Thank you for your hard work and dedication! Respect to you!
